language: cpp
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
    env:
      - CC=gcc-6
      - CXX=g++-6


script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target install
  - cd ../bin
  - ./test
