language: cpp
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6.3


script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target install
  - cd ../bin
  - ./test